name: Rust

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  packages: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: hello-${{ github.sha }}
        path: target/release/hello-world
        retention-days: 1
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: target/release/hello-world
